#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
#use strict;

#
# nethserver-arpwatch-update event
#

my $event = "nethserver-arpwatch-update";

event_actions($event,'initialize-default-databases' => '00');

templates2events("/etc/rc.d/init.d/arpwatch", $event);

event_services($event, 'arpwatch' => 'restart');

#
# actions for nethserver-atpwatch-save event
# don't expand the template here
#

my $event = "nethserver-arpwatch-save";
event_services($event, 'arpwatch' => 'restart');

#Templates to expand
templates2events("/etc/sysconfig/arpwatch", $event);
