#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = "nethserver-arpwatch-update";
event_actions($event,
'initialize-default-databases' => '00');


#Templates to expand
templates2events("/etc/sysconfig/arpwatch", $event);
